<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ADVCTHG" failures="1" tests="6" name="practice_testcases.InvoiceTest2" time="0.036" errors="0" timestamp="04 Mar 2025 07:03:56 GMT" skipped="5">
  <testcase classname="practice_testcases.InvoiceTest2" name="activateSim" time="0.002">
    <failure message="expected [Login] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Login] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at practice_testcases.InvoiceTest2.activateSim(InvoiceTest2.java:11)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- activateSim -->
  <testcase classname="practice_testcases.InvoiceTest2" name="activateSim" time="0.001">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice_testcases.InvoiceTest2" name="activateSim" time="0.002">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice_testcases.InvoiceTest2" name="activateSim" time="0.002">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice_testcases.InvoiceTest2" name="activateSim" time="0.028">
    <skipped/>
  </testcase> <!-- activateSim -->
  <testcase classname="practice_testcases.InvoiceTest2" name="activateSim" time="0.001">
    <skipped/>
  </testcase> <!-- activateSim -->
</testsuite> <!-- practice_testcases.InvoiceTest2 -->
